// APIs.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//base url of api https://api.railmuseumubl.in/api

import Foundation

public class SwaggerClientAPI {
  //  public static var basePath = "https://api.railmuseumubl.in/api"
    public static var basePath = "https://admin.celebrateapp.com"
    public static var credential: URLCredential?
    public static var customHeaders: [String:String] = [:]
    public static var requestBuilderFactory: RequestBuilderFactory = AlamofireRequestBuilderFactory()
}

public class RequestBuilder<T> {
    var credential: URLCredential?
    var headers: [String:String]
    public let parameters: [String:Any?]?
    public let isBody: Bool
    public let method: String
    public let URLString: String

    /// Optional block to obtain a reference to the request's progress instance when available.
    public var onProgressReady: ((Progress) -> ())?

    required public init(method: String, URLString: String, parameters: [String:Any]?, isBody: Bool, headers: [String:String] = [:]) {
        self.method = method
        self.URLString = URLString
        self.parameters = parameters
        self.isBody = isBody
        self.headers = headers
        if let token = User.load()?.token {
            self.headers["x-api-key"] = token
        }else if let otpToken = VerifyMobileViewController.authToken {
            self.headers["x-api-key"] = otpToken
        }
        print("x-api-key \(User.load()?.token ?? "")")
        addHeaders(SwaggerClientAPI.customHeaders)
    }

    public func addHeaders(_ aHeaders:[String:String]) {
        for (header, value) in aHeaders {
            headers[header] = value
        }
    }

    public func execute(isFormData: Bool = false, _ completion: @escaping (_ response: Response<T>?, _ error: Error?) -> Void) { }

    public func addHeader(name: String, value: String) -> Self {
        if !value.isEmpty {
            headers[name] = value
        }
        return self
    }

    public func addCredential() -> Self {
        self.credential = SwaggerClientAPI.credential
        return self
    }
}

public protocol RequestBuilderFactory {
    func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type
    func getBuilder<T:Codable>() -> RequestBuilder<T>.Type
}
