-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkBkJBB1H0UP85fHz
kNkFFGLeXiZTcnANoH7B92FZluegCgYIKoZIzj0DAQehRANCAARL7x7L7XpYzKlg
Yj5BGbOo4ucbWaLZ7qmsHwqEYqrJ5F6h/s0kcxcYiJRGKKY4iPDif6DRFqLcxopf
ASfPGAih
-----END PRIVATE KEY-----